name: ramtha
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.5
  get: ^4.6.5
  intl: ^0.18.1
  package_info_plus: ^4.0.2
  flutter_share: ^2.0.0
  flutter_secure_storage: ^8.0.0
  url_launcher: ^6.1.11
  carousel_slider: ^4.2.1
  mime: ^1.0.4
  smooth_page_indicator: ^1.1.0
  connectivity: ^3.0.6
  google_maps_flutter: ^2.3.0
  #  location: ^4.4.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  flutter_rating_bar: ^4.0.1
  flutter_rounded_date_picker: ^3.0.4
  flutter_svg: ^2.0.7
  http: ^1.0.0
  alice: ^0.3.3
  shared_preferences: ^2.1.2
  cached_network_image: ^3.2.3
  image_picker: ^0.8.9
  firebase_messaging: ^14.6.1
  firebase_core: ^2.13.0

dependency_overrides:
  intl: ^0.18.1
  http: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/


  fonts:
    - family: ArbFONTS
      fonts:
        - asset: fonts/ArbFONTS-4_F0.ttf
        - asset: fonts/ArbFONTS-4_F1.ttf
        - asset: fonts/ArbFONTS-4_F2.ttf
          style: italic