name: ramtha
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.5
  get: ^4.6.5
  intl: ^0.18.1
  package_info_plus: ^4.0.2
  flutter_share: ^2.0.0
  flutter_secure_storage: ^8.0.0
  url_launcher: ^6.1.11
  connectivity: ^3.0.6
  google_maps_flutter: ^2.3.0
  #  location: ^4.4.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  flutter_rating_bar: ^4.0.1
  flutter_rounded_date_picker: ^3.0.4
  flutter_svg: ^2.0.7
  http: ^1.0.0
  alice: ^0.3.3
  shared_preferences: ^2.1.2
  cached_network_image: ^3.2.3
dependency_overrides:
  intl: ^0.18.1
  http: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/


  fonts:
    - family: ArbFONTS
      fonts:
        - asset: fonts/ArbFONTS-4_F0.ttf
        - asset: fonts/ArbFONTS-4_F1.ttf
        - asset: fonts/ArbFONTS-4_F2.ttf
          style: italic